name: EpicUtil
main: me.gmx.epicutil.EpicUtil
version: ${project.version}
author: GMX
commands:
  lore:
    description: Base command for text manipulation.
    usage: /lore rename:set:add:clear:bind:unbreak
  epicutil:
    description: Base command for the plugin
    usage: /epicutil
  mutechat:
    description: Mutes everyone
    usage: /mutechat
    aliases: [globalmute]
  clearchat:
    description: Clears chat
    usage: /clearchat